### ISSUE TITLE
Rename repository to kotlin-hsdp-sdk

### ISSUE THREAD

**Issue by marcofranssen** [philips-software/kotlin-hsdp-sdk#2]
It looks like this repository contains an sdk for the hsdp api.

At first I was confused as the repository name is `kotlin-hsdp-api`.

Shouldn't the repository name be `kotlin-hsdp-sdk`?

**Comment by aadrijnberg** [comment]
I used the same naming scheme as Andy Lo A Foe did for his Go version (go-hsdp-api)
